name: DHR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        
    - name: Build
      run: cmd.exe /c gradlew.bat assembleRelease

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
          name: DHR
          path: "app/build/outputs/apk/release/youtube_pro_signed.apk"
